title: Root
description: At this together.
google_analytics: G-5Q0LBMLZ2B
theme: jekyll-theme-cayman
show_urls: true
github:
  root_url: https://www.imdb.com/title/tt1839578/characters/nm0009918
  shaw_url: https://www.imdb.com/title/tt1839578/characters/nm1083404
  description: We're so good at this together<br>You're gonna realize that someday
